#!/usr/bin/env python3
"""
underwater_gui_enhanced.py

Enhanced GUI for Underwater Communication Scenarios with extended TDMA and Aggregation features:
 - Highlights current TDMA slot (visual glow)
 - Shows active slot info in stats panel
 - Shows aggregation burst details in stats panel
 - Glow animation for transmitting node
 - Buffer fill progress display near nodes
 - Burst count vs time plot

Run:
    python underwater_gui_enhanced.py

Author: ChatGPT (generated)
"""

import os, time, math, random, zipfile
from collections import defaultdict, deque
try:
    import tkinter as tk
    from tkinter import ttk, scrolledtext, messagebox, filedialog
except Exception as e:
    raise RuntimeError("tkinter required. Error: %s" % e)

import matplotlib
matplotlib.use("TkAgg")
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import matplotlib.image as mpimg
import numpy as np
from pathlib import Path

# Paths & assets
AUV_ICON_PATH = "/mnt/data/auv_icon.png"  # generated by the installer
ZIP_PATH = "/mnt/data/iot-hybrid-underwater.zip"
EXTRACT_DIR = "/mnt/data/iot-hybrid-underwater_extracted"

# Simulation parameters (tweakable)
FPS = 30
SIM_DURATION = 20.0
PACKET_GEN_RATE = 0.6
NUM_NODES = 6  # including sink (node 0)

# Energy model
ENERGY_ACOUSTIC = 5.0
ENERGY_OPTICAL = 1.0
ENERGY_IDLE = 0.01

# Colors
COLOR_ACOUSTIC = "tab:blue"
COLOR_OPTICAL = "tab:red"
COLOR_BG = "#002b3a"
PANEL_BG = "#082933"
TEXT_BG = "#031a20"
HIGHLIGHT_COLOR = "#ffdd57"

SCENARIO_INFO = {
    "acoustic": "Slow, long-range, high delay, potential collisions. Acoustic-only links.",
    "hybrid": "Priority-based hybrid: HIGH->Optical (fast, short-range), LOW->Acoustic (slow). Fallback to acoustic on optical failure.",
    "tdma": "TDMA scheduling: nodes transmit only in assigned slots (collision-free). Hybrid channel selection still applies.",
    "aggregation": "Aggregator batches packets and sends bursts -> fewer transmissions but added buffering delay."
}

def attempt_extract_zip():
    if os.path.exists(ZIP_PATH):
        try:
            if not os.path.exists(EXTRACT_DIR):
                os.makedirs(EXTRACT_DIR, exist_ok=True)
                with zipfile.ZipFile(ZIP_PATH, "r") as zf:
                    zf.extractall(EXTRACT_DIR)
            return True
        except Exception as e:
            print("Failed to extract zip:", e)
    return False

class PacketEvent:
    def __init__(self, pkt_id, src, dst, pkt_type, gen_time, size=1):
        self.pkt_id = pkt_id
        self.src = src
        self.dst = dst
        self.pkt_type = pkt_type
        self.gen_time = gen_time
        self.send_time = None
        self.recv_time = None
        self.channel = None

class BaseSimulator:
    def __init__(self, num_nodes=NUM_NODES, duration=SIM_DURATION):
        self.num_nodes = num_nodes
        self.duration = duration
        self.time = 0.0
        self.pkt_counter = 0

    def generate_stream(self):
        raise NotImplementedError

class AcousticSimulator(BaseSimulator):
    def generate_stream(self):
        while self.time < self.duration:
            src = random.randint(1, self.num_nodes-1)
            dst = 0
            pkt_type = "LOW"
            tgap = random.expovariate(PACKET_GEN_RATE)
            self.time += tgap
            self.pkt_counter += 1
            pkt = PacketEvent(self.pkt_counter, src, dst, pkt_type, self.time)
            propagation = 2.0 + random.uniform(0.0, 1.0)
            pkt.send_time = self.time + 0.01
            pkt.recv_time = pkt.send_time + propagation
            pkt.channel = "ACOUSTIC"
            yield pkt

class HybridSimulator(BaseSimulator):
    def generate_stream(self):
        while self.time < self.duration:
            src = random.randint(1, self.num_nodes-1)
            dst = 0
            pkt_type = "HIGH" if random.random() < 0.25 else "LOW"
            tgap = random.expovariate(PACKET_GEN_RATE)
            self.time += tgap
            self.pkt_counter += 1
            pkt = PacketEvent(self.pkt_counter, src, dst, pkt_type, self.time)
            pkt.send_time = self.time + 0.003
            if pkt_type == "HIGH":
                if random.random() < 0.06:
                    pkt.channel = "ACOUSTIC"
                    pkt.recv_time = pkt.send_time + (1.8 + random.random()*0.9)
                else:
                    pkt.channel = "OPTICAL"
                    pkt.recv_time = pkt.send_time + (0.18 + random.random()*0.35)
            else:
                pkt.channel = "ACOUSTIC"
                pkt.recv_time = pkt.send_time + (1.8 + random.random()*1.0)
            yield pkt

class TDMASimulator(HybridSimulator):
    def __init__(self, *a, slot_time=0.8, **kw):
        super().__init__(*a, **kw)
        self.slot_time = slot_time

    def generate_stream(self):
        slot = 1
        while self.time < self.duration:
            owner = ((slot-1) % (self.num_nodes-1)) + 1
            num_pkts = random.choice([0,1,1,2])
            for _ in range(num_pkts):
                src = owner; dst = 0
                pkt_type = "HIGH" if random.random() < 0.35 else "LOW"
                self.pkt_counter += 1
                t_offset = random.random() * self.slot_time
                self.time += t_offset
                pkt = PacketEvent(self.pkt_counter, src, dst, pkt_type, self.time)
                pkt.send_time = self.time + 0.002
                if pkt_type == "HIGH":
                    if random.random() < 0.05:
                        pkt.channel = "ACOUSTIC"
                        pkt.recv_time = pkt.send_time + (1.8 + random.random()*0.8)
                    else:
                        pkt.channel = "OPTICAL"
                        pkt.recv_time = pkt.send_time + (0.18 + random.random()*0.35)
                else:
                    pkt.channel = "ACOUSTIC"
                    pkt.recv_time = pkt.send_time + (1.6 + random.random()*1.0)
                yield pkt
            self.time += max(0.0, self.slot_time*0.5)
            slot += 1

class AggregationSimulator(HybridSimulator):
    def __init__(self, *a, buffer_size=5, buffer_timeout=2.0, **kw):
        super().__init__(*a, **kw)
        self.buffer_size = buffer_size
        self.buffer_timeout = buffer_timeout

    def generate_stream(self):
        buffer = []
        buffer_start = None
        while self.time < self.duration:
            src = random.randint(1, self.num_nodes-1)
            dst = 0
            pkt_type = "HIGH" if random.random() < 0.22 else "LOW"
            tgap = random.expovariate(PACKET_GEN_RATE)
            self.time += tgap
            self.pkt_counter += 1
            pkt = PacketEvent(self.pkt_counter, src, dst, pkt_type, self.time)
            buffer.append(pkt)
            if buffer_start is None:
                buffer_start = self.time
            if len(buffer) >= self.buffer_size or (self.time - buffer_start) >= self.buffer_timeout:
                send_base = self.time + 0.02
                # record burst info in a simple structure returned via packet event attribute 'batch_id'
                batch_id = int(self.time*1000)
                for i,bp in enumerate(buffer):
                    bp.send_time = send_base + 0.001*i
                    bp.batch_id = batch_id
                    if bp.pkt_type == "HIGH":
                        if random.random() < 0.04:
                            bp.channel = "ACOUSTIC"
                            bp.recv_time = bp.send_time + (1.8 + random.random()*0.8)
                        else:
                            bp.channel = "OPTICAL"
                            bp.recv_time = bp.send_time + (0.18 + random.random()*0.35)
                    else:
                        bp.channel = "ACOUSTIC"
                        bp.recv_time = bp.send_time + (1.6 + random.random()*1.0)
                    yield bp
                buffer = []; buffer_start = None
        for i,bp in enumerate(buffer):
            bp.send_time = self.time + 0.01 + 0.001*i
            bp.batch_id = int(self.time*1000)
            if bp.pkt_type == "HIGH":
                bp.channel = "OPTICAL"
                bp.recv_time = bp.send_time + (0.2 + random.random()*0.3)
            else:
                bp.channel = "ACOUSTIC"
                bp.recv_time = bp.send_time + (1.8 + random.random()*1.0)
            yield bp

class UnderwaterGUI(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Underwater Communication Visualizer (Enhanced)")
        self.geometry("1200x780")
        self.configure(bg=COLOR_BG)

        # Left control panel
        self.left_frame = tk.Frame(self, bg=PANEL_BG, width=360, height=760)
        self.left_frame.pack(side=tk.LEFT, fill=tk.Y)

        # Buttons
        btns = [
            ("Run Acoustic Baseline", lambda:self.start_scenario("acoustic")),
            ("Run Hybrid (Priority)", lambda:self.start_scenario("hybrid")),
            ("Run Hybrid + TDMA", lambda:self.start_scenario("tdma")),
            ("Run Hybrid + Aggregation", lambda:self.start_scenario("aggregation")),
            ("Load Simulation Log (JSON)", self.load_log),
            ("Show Energy Graph", self.show_energy_graph),
            ("Show PDR & Throughput", self.show_performance_graph),
            ("Show Latency Comparison", self.show_comparison),
            ("Show Burst History Plot", self.show_burst_history),
            ("Stop Animation", self.stop_animation)
        ]
        for t, cmd in btns:
            b = ttk.Button(self.left_frame, text=t, command=cmd)
            b.pack(padx=12, pady=6, fill=tk.X)

        # Explanation
        lbl = tk.Label(self.left_frame, text="Scenario Explanation", bg=PANEL_BG, fg="white", font=("Helvetica",11,"bold"))
        lbl.pack(padx=12, pady=(12,2), anchor="w")
        self.expl_text = scrolledtext.ScrolledText(self.left_frame, width=40, height=10, wrap=tk.WORD, bg=TEXT_BG, fg="white")
        self.expl_text.pack(padx=12, pady=4)

        # Live stats
        lbl2 = tk.Label(self.left_frame, text="Live Stats", bg=PANEL_BG, fg="white", font=("Helvetica",11,"bold"))
        lbl2.pack(padx=12, pady=(8,2), anchor="w")
        self.stats_text = tk.Text(self.left_frame, height=12, width=40, bg=TEXT_BG, fg="white")
        self.stats_text.pack(padx=12, pady=4)

        # Right: visualization area
        self.fig, self.ax = plt.subplots(figsize=(8,6))
        self.fig.patch.set_facecolor(COLOR_BG)
        self.ax.set_facecolor("#00334d")
        self.canvas = FigureCanvasTkAgg(self.fig, master=self)
        self.canvas.get_tk_widget().pack(side=tk.RIGHT, expand=True, fill=tk.BOTH)

        # animation state
        self.anim = None
        self.events = []
        self.active_particles = []
        self.event_index = 0
        self.anim_time0 = None
        self.start_time = 0.0
        self.scenario_results = {}
        self.node_positions = None

        # pre-init auv_img before drawing
        self.auv_img = None
        if os.path.exists(AUV_ICON_PATH):
            try:
                self.auv_img = mpimg.imread(AUV_ICON_PATH)
            except Exception:
                self.auv_img = None

        # burst history: list of (time, count) for aggregation bursts
        self.burst_history = []

        self.node_positions = self._layout_nodes(NUM_NODES)
        self._draw_static_topology()
        attempt_extract_zip()

        # TDMA runtime variables
        self.tdma_slot_time = 0.8
        self.tdma_slot_owner = None
        self.tdma_slot_start_sim = None
        self.current_tdma_slots_rects = []  # store slot rectangles for highlighting

        # Aggregation runtime tracking for buffer fills: map node -> (buffer_count, buffer_capacity)
        self.agg_buffers = {i: {'count':0, 'capacity':5} for i in range(1, NUM_NODES)}

    def _layout_nodes(self, n):
        positions = {}
        positions[0] = (0.12, 0.5)
        for i in range(1, n):
            angle = math.pi * (i-1) / (n-2) - math.pi/4
            r = 0.35 + 0.06 * ((i-1)%2)
            x = 0.45 + r * math.cos(angle)
            y = 0.5 + r * math.sin(angle)
            positions[i] = (x,y)
        return positions

    def _draw_static_topology(self):
        self.ax.clear()
        self.ax.set_xlim(0,1); self.ax.set_ylim(0,1); self.ax.axis('off')
        # background sea gradient
        self.ax.imshow(np.linspace(0,1,256).reshape(1,-1), extent=[0,1,0,1], aspect='auto', cmap=plt.get_cmap('Blues'), alpha=0.12)
        # draw sink
        sx,sy = self.node_positions[0]
        if self.auv_img is not None:
            im = self.auv_img
            self.ax.imshow(im, extent=[sx-0.04, sx+0.04, sy-0.04, sy+0.04], zorder=5)
            self.ax.text(sx, sy-0.08, "Sink", ha="center", color="w")
        else:
            self.ax.scatter([sx],[sy], s=260, color="gold", edgecolor="k", zorder=4)
            self.ax.text(sx, sy-0.07, "Sink", ha="center", color="white")
        # nodes
        for nid,pos in self.node_positions.items():
            if nid==0: continue
            x,y = pos
            if self.auv_img is not None:
                self.ax.imshow(self.auv_img, extent=[x-0.03, x+0.03, y-0.03, y+0.03], zorder=4)
            else:
                self.ax.scatter([x],[y], s=120, color="#48bfe3", edgecolor="k", zorder=3)
            self.ax.text(x, y-0.06, f"N{nid}", ha="center", color="white", fontsize=8)
            # acoustic link
            sx,sy = self.node_positions[0]
            self.ax.plot([x,sx],[y,sy], linestyle=(0,(5,8)), color=COLOR_ACOUSTIC, linewidth=1.0, alpha=0.6)
            # optical hint if near
            dist = math.hypot(x-sx, y-sy)
            if dist < 0.7:
                self.ax.plot([x,sx],[y,sy], linestyle='-', color=COLOR_OPTICAL, linewidth=1.4, alpha=0.18)

    def start_scenario(self, name):
        if self.anim:
            messagebox.showinfo("Running", "Stop the current animation first.")
            return
        if name == "acoustic":
            sim = AcousticSimulator()
            expl = "Acoustic Baseline:\n\n" + SCENARIO_INFO["acoustic"]
        elif name == "hybrid":
            sim = HybridSimulator()
            expl = "Hybrid (Priority):\n\n" + SCENARIO_INFO["hybrid"]
        elif name == "tdma":
            sim = TDMASimulator()
            expl = "Hybrid + TDMA:\n\n" + SCENARIO_INFO["tdma"]
        elif name == "aggregation":
            sim = AggregationSimulator()
            expl = "Hybrid + Aggregation:\n\n" + SCENARIO_INFO["aggregation"]
        else:
            return
        self.expl_text.delete("1.0", tk.END)
        self.expl_text.insert(tk.END, expl + "\n\nSummary:\n" + SCENARIO_INFO.get(name,""))
        self.stats_text.delete("1.0", tk.END)
        self.stats_text.insert(tk.END, "Generating events...\n")
        events = []
        # reset agg buffers and burst history for a fresh run
        self.burst_history = []
        for k in self.agg_buffers:
            self.agg_buffers[k]['count'] = 0
        # generate events
        for pkt in sim.generate_stream():
            # if aggregation simulator, update buffer counts for visualization: we approximate buffer behavior by batch ids
            if hasattr(pkt, 'batch_id'):
                # count will be handled when animating
                pass
            events.append(pkt)
        self.scenario_results[name] = self._compute_results(events)
        self._start_animation_with_events(events, scenario=name)

    def _compute_results(self, events):
        stats = {"n_packets": len(events), "by_channel": defaultdict(int)}
        latencies = []
        energy = 0.0
        for e in events:
            if e.send_time and e.recv_time:
                lat = e.recv_time - e.gen_time
                latencies.append(lat)
            if e.channel == "ACOUSTIC":
                stats["by_channel"]["ACOUSTIC"] += 1
                energy += ENERGY_ACOUSTIC
            elif e.channel == "OPTICAL":
                stats["by_channel"]["OPTICAL"] += 1
                energy += ENERGY_OPTICAL
        stats["avg_latency"] = (sum(latencies)/len(latencies)) if latencies else 0.0
        stats["latency_list"] = latencies
        stats["energy"] = energy
        stats["pdr"] = (len(latencies) / max(1, stats["n_packets"])) if stats["n_packets"]>0 else 0.0
        stats["throughput"] = stats["n_packets"] / SIM_DURATION
        return stats

    def _start_animation_with_events(self, events, scenario="sim"):
        self.events = sorted(events, key=lambda e: e.send_time if e.send_time is not None else e.gen_time)
        if not self.events:
            messagebox.showinfo("No events", "No packets were generated for this scenario.")
            return
        self.active_particles = []
        self.event_index = 0
        self.anim_time0 = time.time()
        self.start_time = self.events[0].send_time or self.events[0].gen_time
        self._draw_static_topology()
        # if TDMA, draw timeline rectangles and store them for highlighting
        self.current_tdma_slots_rects = []
        if scenario == "tdma":
            timeline_y = 0.06
            xs = np.linspace(0.15,0.95, len(self.node_positions))
            for i in range(1, len(self.node_positions)):
                rect = plt.Rectangle((xs[i-1]-0.03, timeline_y), 0.06, 0.02, color="#154850", alpha=0.9, zorder=2)
                self.ax.add_patch(rect)
                self.ax.text(xs[i-1], timeline_y+0.03, f"Slot {i}", color="white", ha="center", fontsize=8)
                self.current_tdma_slots_rects.append((rect, i))
            # initialize tdma slot timing
            self.tdma_slot_time = 0.8
            self.tdma_slot_owner = 1
            self.tdma_slot_start_sim = self.start_time
        # start animation
        self.anim = FuncAnimation(self.fig, self._anim_step, interval=1000/FPS, blit=False)
        self.canvas.draw()

    def _anim_step(self, frame):
        now = time.time()
        wall_elapsed = now - self.anim_time0
        sim_elapsed = wall_elapsed
        # Manage TDMA highlighting: compute current slot if rectangles are present
        if self.current_tdma_slots_rects:
            # determine which slot index is active based on elapsed time
            slot_duration = self.tdma_slot_time
            elapsed_since_start = sim_elapsed
            # cycle through slots (1..N-1)
            nslots = len(self.current_tdma_slots_rects)
            # compute slot index (0-based)
            slot_index = int(elapsed_since_start // slot_duration) % nslots
            active_slot = self.current_tdma_slots_rects[slot_index][1]
            # update tdma runtime variables
            self.tdma_slot_owner = active_slot
            # highlight rectangles: active glows, others dim
            for idx, (rect, slotnum) in enumerate(self.current_tdma_slots_rects):
                if slotnum == active_slot:
                    rect.set_alpha(0.95)
                    rect.set_facecolor(HIGHLIGHT_COLOR)
                else:
                    rect.set_alpha(0.6)
                    rect.set_facecolor("#154850")
            # show active slot info in stats panel (top)
            time_into_slot = elapsed_since_start % slot_duration
            time_left = max(0.0, slot_duration - time_into_slot)
            header = f"TDMA Active Slot: {active_slot} | Owner: N{active_slot} | Time left in slot: {time_left:.2f}s\n"
            # replace first line in stats_text with header (keep rest)
            content = self.stats_text.get("1.0", tk.END).splitlines()
            # keep up to 50 lines to avoid uncontrolled growth
            rest = "\\n".join(content[1:50]) if len(content)>1 else ""
            self.stats_text.delete("1.0", tk.END)
            self.stats_text.insert(tk.END, header + rest)
        # spawn new events
        while self.event_index < len(self.events) and (self.events[self.event_index].send_time - self.start_time) <= sim_elapsed:
            e = self.events[self.event_index]
            src = self.node_positions[e.src]; dst = self.node_positions[e.dst]
            lifetime = max(0.2, (e.recv_time - e.send_time))
            color = COLOR_OPTICAL if e.channel == "OPTICAL" else COLOR_ACOUSTIC
            marker = "D" if e.pkt_type=="HIGH" else "o"
            p = {"event": e, "src": src, "dst": dst, "t0": sim_elapsed, "lifetime": lifetime, "color": color, "marker": marker}
            # If aggregation event has batch_id, record burst and show buffer info
            if hasattr(e, 'batch_id'):
                # find how many events share this batch_id (count in full events list)
                batch_id = e.batch_id
                batch_count = sum(1 for ev in self.events if hasattr(ev, 'batch_id') and ev.batch_id==batch_id)
                # record burst (only record once per batch by checking first occurrence)
                if not any(bh[2]==batch_id for bh in self.burst_history):
                    burst_time = self.start_time + (e.send_time - e.send_time)  # approximate as send time
                    self.burst_history.append((time.time(), batch_count, batch_id))
                    # display burst details in stats
                    self.stats_text.insert(tk.END, f"Aggregation Burst at Node N{e.src}: Packets={batch_count} | BatchID={batch_id}\\n")
                    # update buffer display: reset buffer count for that node (since they were flushed)
                    if e.src in self.agg_buffers:
                        self.agg_buffers[e.src]['count'] = 0
            # For aggregation simulation, we also simulate buffer fill increments before send
            # We'll increase buffer count for the source node if scenario contains aggregation
            self.active_particles.append(p)
            self.event_index += 1
        # redraw topology
        self._draw_static_topology()
        # draw buffer fill progress near nodes (visual)
        for nid, buf in self.agg_buffers.items():
            if buf['count'] > 0:
                x,y = self.node_positions[nid]
                self.ax.text(x, y+0.05, f"Buf {buf['count']}/{buf['capacity']}", color="yellow", fontsize=7, ha="center")
        # draw active particles and node glows for transmitting nodes
        to_remove = []
        transmitting_nodes = set()
        for p in self.active_particles:
            t = sim_elapsed - p["t0"]
            frac = min(1.0, t / p["lifetime"])
            sx,sy = p["src"]; dx,dy = p["dst"]
            x = sx + (dx-sx)*frac; y = sy + (dy-sy)*frac
            self.ax.scatter([x],[y], s=80, color=p["color"], zorder=6, marker=p["marker"], edgecolor="k")
            # if still in flight near source (<20% progress), consider source as transmitting (for glow)
            if frac < 0.2:
                transmitting_nodes.add(p["event"].src)
            if p["event"].pkt_type=="HIGH" and p["event"].channel=="ACOUSTIC" and t<0.12:
                self.ax.text(x, y+0.04, "fallback", color="yellow", fontsize=7, ha="center")
            if frac >= 1.0:
                to_remove.append(p)
                ev = p["event"]
                latency = (ev.recv_time - ev.gen_time) if ev.recv_time else 0.0
                self.stats_text.insert(tk.END, f"Pkt {ev.pkt_id} | {ev.pkt_type} | {ev.channel} | latency={latency:.2f}s\\n")
                self.stats_text.see(tk.END)
        # draw glow around transmitting nodes (pulsing)
        pulse = 0.5 + 0.5 * math.sin(time.time()*6.0)
        for nid in transmitting_nodes:
            x,y = self.node_positions[nid]
            glow_r = 0.05 * (1.0 + pulse)
            circle = plt.Circle((x,y), glow_r, color=HIGHLIGHT_COLOR, alpha=0.18 + 0.12*pulse, zorder=2)
            self.ax.add_patch(circle)
        for p in to_remove:
            self.active_particles.remove(p)
        # Update buffer fill progress heuristically: if many future events belong to same batch, increase count
        # This is a visual heuristic: detect upcoming batch_ids and increment buffer counts before send
        upcoming_batches = {}
        for idx in range(self.event_index, min(len(self.events), self.event_index+40)):
            ev = self.events[idx]
            if hasattr(ev, 'batch_id'):
                upcoming_batches.setdefault((ev.src, ev.batch_id), 0)
                upcoming_batches[(ev.src, ev.batch_id)] += 1
        # Set agg_buffers counts based on upcoming_batches (visual only)
        for (src, bid), cnt in upcoming_batches.items():
            if src in self.agg_buffers:
                self.agg_buffers[src]['count'] = min(self.agg_buffers[src]['capacity'], cnt)
        # draw canvas
        self.canvas.draw()
        # check finish
        if self.event_index >= len(self.events) and not self.active_particles:
            if self.anim:
                try: self.anim.event_source.stop()
                except Exception: pass
            last = self._compute_results(self.events)
            self.stats_text.insert(tk.END, "\nSummary:\n")
            self.stats_text.insert(tk.END, f"Packets: {last['n_packets']}\nAvg latency: {last['avg_latency']:.2f}s\nBy channel: {dict(last['by_channel'])}\nEnergy: {last['energy']:.2f} J\nPDR: {last['pdr']:.2f}\nThroughput: {last['throughput']:.2f} pkts/s\n")
            self.stats_text.see(tk.END)
            self.anim = None
        return []

    def pkt_delivered_count(self):
        if not self.events: return 0
        now = time.time(); sim_elapsed = now - self.anim_time0; cutoff = self.start_time + sim_elapsed
        return sum(1 for e in self.events if e.recv_time and e.recv_time <= cutoff)

    def _compute_avg_latency_so_far(self):
        if not self.events: return 0.0
        now = time.time(); sim_elapsed = now - self.anim_time0; cutoff = self.start_time + sim_elapsed
        lats = [(e.recv_time - e.gen_time) for e in self.events if e.recv_time and e.recv_time <= cutoff]
        return (sum(lats)/len(lats)) if lats else 0.0

    def show_comparison(self):
        scenarios = ["acoustic","hybrid","tdma","aggregation"]
        present = [s for s in scenarios if s in self.scenario_results]
        if not present:
            messagebox.showinfo("No data", "Run each scenario once to collect results, then click this button.")
            return
        win = tk.Toplevel(self); win.title("Latency Comparison")
        fig, ax = plt.subplots(figsize=(7,4)); fig.patch.set_facecolor(COLOR_BG); ax.set_facecolor("#002b3a")
        labels = []; means = []
        for s in present:
            res = self.scenario_results[s]; labels.append(s); means.append(res["avg_latency"])
        ax.bar(labels, means); ax.set_ylabel("Average latency (s)"); ax.set_title("Avg latency per scenario")
        canvas = FigureCanvasTkAgg(fig, master=win); canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True); canvas.draw()

    def show_energy_graph(self):
        if not self.scenario_results:
            messagebox.showinfo("No data", "Run scenarios first to collect energy data.")
            return
        win = tk.Toplevel(self); win.title("Energy Consumption")
        fig, ax = plt.subplots(figsize=(7,4)); fig.patch.set_facecolor(COLOR_BG); ax.set_facecolor("#002b3a")
        labels = list(self.scenario_results.keys()); values = [self.scenario_results[s]["energy"] for s in labels]
        ax.bar(labels, values); ax.set_ylabel("Energy (J)"); ax.set_title("Energy Consumption per Scenario")
        canvas = FigureCanvasTkAgg(fig, master=win); canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True); canvas.draw()

    def show_performance_graph(self):
        if not self.scenario_results:
            messagebox.showinfo("No data", "Run scenarios first to collect performance data.")
            return
        win = tk.Toplevel(self); win.title("Performance Metrics")
        fig, ax = plt.subplots(1,2, figsize=(10,4)); fig.patch.set_facecolor(COLOR_BG); ax[0].set_facecolor("#002b3a"); ax[1].set_facecolor("#002b3a")
        labels = list(self.scenario_results.keys()); pdr = [self.scenario_results[s]["pdr"] for s in labels]; thr = [self.scenario_results[s]["throughput"] for s in labels]
        ax[0].bar(labels, pdr); ax[0].set_title("Packet Delivery Ratio"); ax[1].bar(labels, thr); ax[1].set_title("Throughput (pkts/s)")
        canvas = FigureCanvasTkAgg(fig, master=win); canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True); canvas.draw()

    def load_log(self):
        path = filedialog.askopenfilename(title="Open JSON log", filetypes=[("JSON files","*.json"),("All files","*.*")])
        if not path: return
        try:
            import json
            with open(path,"r") as f:
                data = json.load(f)
            events = []
            for item in data.get("events", []):
                pkt = PacketEvent(item.get("id",0), item.get("src",1), item.get("dst",0), item.get("type","LOW"), item.get("gen",0.0))
                pkt.send_time = item.get("send", pkt.gen_time)
                pkt.recv_time = item.get("recv", pkt.send_time + 1.0)
                pkt.channel = item.get("channel", "ACOUSTIC")
                # preserve batch_id if provided
                if "batch_id" in item:
                    pkt.batch_id = item["batch_id"]
                events.append(pkt)
            name = os.path.splitext(os.path.basename(path))[0]
            self.scenario_results[name] = self._compute_results(events)
            self.expl_text.delete("1.0", tk.END); self.expl_text.insert(tk.END, f"Loaded log: {path}\\nEvents: {len(events)}\\nReplaying...")
            self._start_animation_with_events(events, scenario=name)
        except Exception as e:
            messagebox.showerror("Error", f"Failed to load log: {e}")

    def stop_animation(self):
        if self.anim:
            try: self.anim.event_source.stop()
            except Exception: pass
            self.anim = None
        self.events = []; self.active_particles = []; self.event_index = 0
        self.stats_text.insert(tk.END, "\\nAnimation stopped.\\n")

    def show_burst_history(self):
        if not self.burst_history:
            messagebox.showinfo("No data", "No bursts recorded yet. Run an aggregation scenario to collect bursts.")
            return
        times = [t[0] for t in self.burst_history]
        counts = [t[1] for t in self.burst_history]
        win = tk.Toplevel(self); win.title("Burst History")
        fig, ax = plt.subplots(figsize=(7,4)); fig.patch.set_facecolor(COLOR_BG); ax.set_facecolor("#002b3a")
        ax.plot(range(len(counts)), counts, marker='o')
        ax.set_xlabel("Burst Index"); ax.set_ylabel("Packets in Burst")
        ax.set_title("Burst Count vs Time (indexed)")
        canvas = FigureCanvasTkAgg(fig, master=win); canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True); canvas.draw()

def main():
    app = UnderwaterGUI(); app.mainloop()

if __name__ == "__main__":
    main()
